### ISSUE TITLE
Installation script changes user's global git configuration

### ISSUE THREAD

**Issue by michalsz2** [markriley9999/refPlayer#12]
In /install/git-pull.sh, which is executed by /install/install-2.sh, there are lines:
```
git config --global user.name "manufacturer"
git config --global user.email manufacturer@digitaluk.co.uk
```
This should not be used, as it changes user's global git configuration.

**Comment by markriley9999** [comment]
Good point - I'll fix it for the next release.

**Comment by markriley9999** [comment]
Fixed
